### ISSUE TITLE
窗格拆分是什么？

### ISSUE THREAD

**Issue by DrayChou** [chinakids/atom-simplified-chinese-menu#11]
需要安装对应的插件吗？我现在点了这个选项就会卡死 atom

**Comment by chinakids** [comment]
打开多个面板，我这里不会卡死，请提交对应atom版本，系统版本

**Comment by DrayChou** [comment]
windows 7 专业版
atom 1.3.2

Geron <notifications@github.com> 於 2015年12月31日 週四 下午8:22寫道：

**Comment by chinakids** [comment]
@DrayChou 是崩溃，还是直接卡死？建议提交issues到官方，本插件并不会干预功能层面，您可以尝试下关闭翻译后看是否崩溃，如果依旧崩溃  建议重装试试

**Comment by DrayChou** [comment]
哦哦，我以为是这个插件带的功能，我错了。
关闭插件之后，再次拆分还是会卡死，就是一段时间没有反应然后弹出提示是继续等待还是关闭。
这个 issues 关闭好了，我待会提到官方去。

Geron <notifications@github.com> 於 2015年12月31日 週四 下午8:30寫道：
