### ISSUE TITLE
扩展设置切换至其他标签页再切回来, 会跳至安装页

### ISSUE THREAD

**Issue by 17** [chinakids/atom-simplified-chinese-menu#13]
![gif](https://cloud.githubusercontent.com/assets/6132593/12295988/b24b7ba0-ba3f-11e5-9cf4-2711bdade8cd.gif)

**具体步骤**: 
设置页面 > 扩展 > 进入任意扩展设置 > 切换到其他标签页 > 返回设置标签
(会丢失设置页状态并跳至安装页)

**Comment by chinakids** [comment]
好的   我正在排插此问题，如果顺利将在下版本发布时修复
