### ISSUE TITLE
mac 3.4.6 下未翻译词条

### ISSUE THREAD

**Issue by chenjau** [chinakids/atom-simplified-chinese-menu#18]
atom 主菜单下的
  Config...
  Init Script...
  Keymap...
  Snippets...
  Stylesheet...

文件菜单下的
  Close All Tabs

edit: close all tabs 在 atom 的源码里都查不到, 基本不可翻了吧?

**Comment by chinakids** [comment]
有些事为了兼容以前的,没有的词条不带便不在其他版本出现,另外你说的这些都有啊，你看看是不是设置没开启，或者重新安装试试，本插件依赖的cson模块有的时候需要VPN才能安装上
