### ISSUE TITLE
最新版本3.4.9问题

### ISSUE THREAD

**Issue by lxtac** [chinakids/atom-simplified-chinese-menu#22]
首先对于制作者表示敬意~~~~

然后给一些目前出现的问题：
首先，我使用的是 Mac 平台！

1、该插件设置中的“Uninstall”、“Disable”和“Enable”三个选项没有汉化；
2、Mac 版本Atorm的主菜单中 “Version” 应汉化成“版本”，这样会显示为“版本 X.X.X” 更加完美；
3、Mac 版本Atorm的主菜单中 “Services” 应汉化成“服务”；
3、Mac 版本Atorm的主菜单中 “首选项” 应汉化成“偏好设置”；
4、“显示全部窗口”→
“全部显示”；
5、“最小化其他窗口”→“隐藏其他”；

如此，则您制作的软件，已经近乎完美。

**Comment by chinakids** [comment]
感谢您的建议
下面回复您提的几个意见

1.首次进入这个三个是汉化过的,如果搜索过会导致列表重载,按钮汉化失效,目前也在思考比较好的解决方案
2.已经采纳，下一版本(3.4.10)会更新
3.已经采纳，下一版本(3.4.10)会更新
4.已经采纳，下一版本(3.4.10)会更新
5.6. 为了避免歧义，暂时不会改动

再次感谢您的建议

**Comment by vlongen** [comment]
最小化窗口 这个之所以要显示为 隐藏其他，请参照Mac原生应用Finder的官方翻译，它由Apple官方开发，因此所有汉化软件都应以Mac的统一翻译为标准术语！

我也做过很多汉化包，深知其辛苦，谢谢您的贡献！

发自我的 iPhone

**Comment by chinakids** [comment]
好
