### ISSUE TITLE
atom 1.9.0-dev 未汉化条目以及性能问题

### ISSUE THREAD

**Issue by chenjau** [chinakids/atom-simplified-chinese-menu#25]
首先感谢作者的劳动.

版本 atom 1.9.0-dev.
系统 macosx 10.11.5.
未汉化条目:
  主菜单:
      编辑 -> Columns
                -> move selection left
                -> move selection right
      查看 -> 开发
                -> reload window
      查找 -> clear history
  编辑窗口右键菜单:
      split up
      split down
      split left
      split right
      (以上四条其实已经汉化, 汉化的四条处于菜单最下面, 但是上面的4条英文还是存在, 且功能一样.)

另外问下有性能优化计划吗? timecop 显示插件载入时间比较长. 基本都是80ms 以上.

**Comment by chinakids** [comment]
请下载v5.3.2版本已经新增翻译，性能能优化有时间再做，settings汉化部分官方没有给方案，是通过操作dom解决的，这块比较慢
