### ISSUE TITLE
mac osx 10.11 设置处的菜单无法汉化，windows可以

### ISSUE THREAD

**Issue by niu541412** [chinakids/atom-simplified-chinese-menu#29]
卸载再安装也不行，测试了包库里的atom-japanese-menu和繁中cht-menu，前者同样问题，后者可以。

<img width="757" alt="2016-09-06 12 09 38" src="https://cloud.githubusercontent.com/assets/3370897/18261460/1aaaf860-742b-11e6-8d51-3335c5a52610.png">

**Comment by niu541412** [comment]
刚才测试了linux版本，也有这问题，设置部分没汉化 Ubuntu16.04 x64

**Comment by chinakids** [comment]
后续版本我会来处理这个问题

**Comment by xhxu** [comment]
<img width="1196" alt="qq20161018-0 2x" src="https://cloud.githubusercontent.com/assets/1581775/19584614/553f5dfc-9778-11e6-9b5a-8a56bc005036.png">
可能是这个问题引起的吧。我这里也是不能汉化设置处左侧

**Comment by chinakids** [comment]
请下载v5.3.2版本已修复
