### ISSUE TITLE
无法汉化

### ISSUE THREAD

**Issue by huangzengsheng** [chinakids/atom-simplified-chinese-menu#31]
atom版本是1.10.2
安装atom-simplified-chinese-menu依然没有变化。重新安装atom也没用，删了.atom重新安装也没发汉化。
![default](https://cloud.githubusercontent.com/assets/22415536/18809302/53dcd846-82aa-11e6-9b82-b209a34151c1.PNG)

**Comment by LexBacker** [comment]
同样的问题

**Comment by weiqiuair** [comment]
同样的问题

**Comment by gendrybaratheon** [comment]
有时候得翻墙吧

**Comment by chinakids** [comment]
请下载v5.3.2版本已修复，新版本已经不需要翻墙
