### ISSUE TITLE
能否汉化菜单栏-插件包。

### ISSUE THREAD

**Issue by kuailel45** [chinakids/atom-simplified-chinese-menu#40]
能否汉化菜单栏-插件包。Mac下现在就是菜单栏-插件包没有汉化，可以汉化吗？
![image](https://cloud.githubusercontent.com/assets/17819498/25516905/876890fa-2c1f-11e7-8f65-e45c5933d80a.png)

**Comment by chinakids** [comment]
插件千千万，何时才是头 
------------------ Original ------------------
