### ISSUE TITLE
右键菜单无汉化

### ISSUE THREAD

**Issue by Chinalink** [chinakids/atom-simplified-chinese-menu#44]
系统：WIN7 64位旗舰版
ATOM版本：1.17.1  X64  
问题原因：左侧目录文件，右键菜单只剩最后一个关闭窗格有汉化，其他均无。顶部菜单无任何问题。
公司重装没有用。

**Comment by imbyron** [comment]
Windows 64 同样问题。

**Comment by chinakids** [comment]
稍后处理

**Comment by chinakids** [comment]
请下载v5.3.2版本已修复
