### ISSUE TITLE
右键菜单文字错误

### ISSUE THREAD

**Issue by Iamlars** [chinakids/atom-simplified-chinese-menu#7]
对文档点击右键的列表中，“移动”  应该是  “重命名”。麻烦大大看一下！

**Comment by chinakids** [comment]
好的，我稍后会检查 
------------------ Original ------------------

**Comment by chinakids** [comment]
经过查证，此多处区域包含此按钮功能，官方名称为 move,实际功能为`复制新建并删除源文件`，因为从官方调用的控件与源单词来说不只可以修改名称，还可以修改路径，经过考虑决定暂定名为`重命名或移动`，修复版本将在下一版本发布
