### ISSUE TITLE
如何安装使用？

### ISSUE THREAD

**Issue by lizhuangs** [chinakids/atom-simplified-chinese-menu#8]
看了好几个国际化插件了，atom没怎么研究过，一个小白问题，就是想知道如何安装汉化包？能否列出一二来。多谢。

**Comment by chinakids** [comment]
软件设置中install 页面搜索需要的包安装，或者安装atom命令行工具后使用apm install <package name>安装
------------------ Original ------------------

**Comment by yqlizeao** [comment]
@chinakids 你好，帮我看看是什么原因，能帮我解决吗
![image](https://cloud.githubusercontent.com/assets/16096037/11494744/53a85aa8-9840-11e5-9189-4f36d147cff0.png)

**Comment by chinakids** [comment]
[@yqlizeao](https://github.com/yqlizeao)貌似没装gyp吧 node你装了么

**Comment by yqlizeao** [comment]
@chinakids 是node-gyp吗，我不懂诶，能具体说说嘛

**Comment by chinakids** [comment]
@yqlizeao 挂上VPN试试

**Comment by yqlizeao** [comment]
@chinakids 不好意思我是新手，插件都不会安装，你可以给我讲讲要怎么弄吗

**Comment by yqlizeao** [comment]
@chinakids 我就在官网下载安装了atom，然后搜索插线安装 ，发现安装不上；我电脑上面安装了VS2013,你说的nodegyp是什么 要怎么安装 可以教我吗

**Comment by chinakids** [comment]
@yqlizeao nodejs安装了没？没安装先安装，安装了挂上vpn试试

**Comment by lizhuangs** [comment]
好吧，怪不得我之前的不行。貌似被墙了，敢问有离线安装方法没有。这又是一个淡疼的问题了。

**Comment by chinakids** [comment]
@lizhuangs 目前没有提供离线安装的包

**Comment by yqlizeao** [comment]
@chinakids 你好 ，我安装了node-js 也安装了git 要如何安装插件，比如简单的emmet  我是一点都不会操作，你能截图逐步说明方法吗？非常感谢！

**Comment by chinakids** [comment]
![image](http://chinakids.github.io/PicturesStore/issues/atom-pakage-install.png)

@yqlizeao 打开设置，侧边栏最下面一个 install，进去了搜索你需要的包，点 install

**Comment by godfather1103** [comment]
@yqlizeao 因为atom托管插件的网站是被墙了的，所以最好的方式就是离线安装，
首先用git clone插件到atom的packages文件夹下（路径为：个人主目录/.atom/packages）,
打开dos或者终端进入要安装的插件的文件夹中，输入apm install（如果安装了npm也可以用npm install），重启atom就安装成功了

**Comment by chinakids** [comment]
是不是真该搞个离线包出来....

**Comment by godfather1103** [comment]
什么意思？

**Comment by yqlizeao** [comment]
@chinakids 希望有离线包

**Comment by yqlizeao** [comment]
@godfather1103 你能一步步截图说明吗，我不知道怎么操作，谢谢了

**Comment by chinakids** [comment]
@yqlizeao .....挂个vpn或者翻个墙有那么难么

**Comment by godfather1103** [comment]
@yqlizeao 我这儿上传不了图片
，所以就这样吧http://my.oschina.net/godfather1103/blog/539608

**Comment by godfather1103** [comment]
@chinakids 关键是翻墙这个速度好慢啊，不如离线安装快啊！

**Comment by licretey** [comment]
我的deepin系统，开始装不上去，就用楼上@godfather1103 commented on 5 Dec 2015大佬的

**Comment by RenSLei** [comment]
@yqlizeao 答主那个截图回答得很清楚啦。至于你这个问题，你多试几次，我的第三次就安装成功
